import type { AnschriftenfeldTask } from './types';

const SENDER = 'Markus Mustermann, Musterstraße 1, 11111 Musterstadt';

export const ANSCHRIFTENFELD_TASKS: AnschriftenfeldTask[] = [
  {
    id: 'privatperson-einfach',
    title: 'Privatperson ohne Titel',
    difficulty: 'einfach',
    arbeitsauftrag:
      'Dein Chef kommt kurz an deinen Schreibtisch und bittet dich, für ihn einen privaten Brief zu adressieren. Er erzählt dir, dass er gestern mit Herrn Stephan Breitner telefoniert hat, der im Birkenweg 11 in 54344 Kenn wohnt, und dass diesem nun die versprochenen Unterlagen zugeschickt werden sollen. Erstelle aus diesen Angaben das vollständige Anschriftenfeld für Herrn Breitner.',
    senderLine: SENDER,
    lines: [
      {
        type: 'text',
        id: 'anrede',
        caption: 'Zeile 6 – Anrede',
        zone: 'anschrift',
        expected: 'Herrn',
        explanation: 'Die Anrede an männliche Empfänger lautet aus grammatikalischen Gründen „Herrn“ und nicht „Herr“.',
      },
      {
        type: 'text',
        id: 'name',
        caption: 'Zeile 7 – Titel Vorname Nachname',
        zone: 'anschrift',
        expected: 'Stephan Breitner',
        explanation: 'Vor- und Nachname stehen in einer eigenen Zeile, ohne Wiederholung der Anrede.',
      },
      {
        type: 'text',
        id: 'strasse',
        caption: 'Zeile 8 – Straße Hausnummer',
        zone: 'anschrift',
        expected: 'Birkenweg 11',
        explanation: 'Straße und Hausnummer stehen ohne Komma, die Hausnummer folgt der Straße.',
      },
      {
        type: 'text',
        id: 'ort',
        caption: 'Zeile 9 – PLZ Ort',
        zone: 'anschrift',
        expected: '54344 Kenn',
        explanation: 'Die Postleitzahl steht immer vor dem Ort, ohne Komma dazwischen.',
      },
    ],
  },
  {
    id: 'privatperson-titel',
    title: 'Privatperson mit Titel',
    difficulty: 'einfach',
    arbeitsauftrag:
      'Deine Chefin bittet dich, einen Brief an eine ehemalige Studienkollegin zu adressieren. Sie erwähnt, dass Frau Dr. Stephanie Breitner mittlerweile im Birkenweg 11 in 54344 Kenn wohnt – in dasselbe Haus, in dem früher ihr Bruder Stephan gewohnt hatte, der aber vor einigen Jahren weggezogen ist. Adressiere den Brief an Frau Dr. Breitner, nicht an ihren Bruder.',
    senderLine: SENDER,
    lines: [
      {
        type: 'text',
        id: 'anrede',
        caption: 'Zeile 6 – Anrede',
        zone: 'anschrift',
        expected: 'Frau',
        explanation: 'Die Anrede an weibliche Empfänger bleibt unverändert „Frau“ (anders als bei „Herrn“).',
      },
      {
        type: 'text',
        id: 'name',
        caption: 'Zeile 7 – Titel Vorname Nachname',
        zone: 'anschrift',
        expected: 'Dr. Stephanie Breitner',
        explanation:
          'Titel stehen mit einem Leerzeichen vor dem Vornamen. Die Anrede aus Zeile 6 wird hier nicht wiederholt.',
      },
      {
        type: 'text',
        id: 'strasse',
        caption: 'Zeile 8 – Straße Hausnummer',
        zone: 'anschrift',
        expected: 'Birkenweg 11',
        explanation: 'Straße und Hausnummer stehen ohne Komma, die Hausnummer folgt der Straße.',
      },
      {
        type: 'text',
        id: 'ort',
        caption: 'Zeile 9 – PLZ Ort',
        zone: 'anschrift',
        expected: '54344 Kenn',
        explanation: 'Die Postleitzahl steht immer vor dem Ort, ohne Komma dazwischen.',
      },
    ],
  },
  {
    id: 'berufsbezeichnung-postfach',
    title: 'Berufsbezeichnung und Postfach',
    difficulty: 'mittel',
    arbeitsauftrag:
      'Dein Chef benötigt rechtlichen Rat in einer Vertragsangelegenheit und hat sich dafür an Herrn Rechtsanwalt Dr. Stephan Breitner gewandt. Da dessen Kanzlei ihre Post ausschließlich über ein Postfach entgegennimmt, notiert dir dein Chef: Postfach 31020, 54345 Kenn. Erstelle daraus die vollständige Anschrift – denk daran, dass die Berufsbezeichnung mit in die Anschrift gehört.',
    senderLine: SENDER,
    lines: [
      {
        type: 'text',
        id: 'anrede',
        caption: 'Zeile 6 – Anrede Berufsbezeichnung',
        zone: 'anschrift',
        expected: 'Herrn Rechtsanwalt',
        explanation: 'Berufs- bzw. Amtsbezeichnungen stehen in derselben Zeile hinter der Anrede.',
      },
      {
        type: 'text',
        id: 'name',
        caption: 'Zeile 7 – Titel Vorname Nachname',
        zone: 'anschrift',
        expected: 'Dr. Stephan Breitner',
        explanation: 'Titel stehen mit Leerzeichen vor dem Vornamen.',
      },
      {
        type: 'text',
        id: 'postfach',
        caption: 'Zeile 8 – Straße Hausnummer (oder Postfach)',
        zone: 'anschrift',
        expected: 'Postfach 3 10 20',
        explanation:
          'Postfachnummern werden von rechts nach links in Zweiergruppen gegliedert – so wie eine Telefonnummer.',
      },
      {
        type: 'text',
        id: 'ort',
        caption: 'Zeile 9 – PLZ Ort',
        zone: 'anschrift',
        expected: '54345 Kenn',
        explanation: 'Die Postleitzahl steht immer vor dem Ort, ohne Komma dazwischen.',
      },
    ],
  },
  {
    id: 'unternehmen-ohne-ansprechpartner',
    title: 'Unternehmen ohne Ansprechpartner',
    difficulty: 'mittel',
    arbeitsauftrag:
      'Dein Chef möchte eine Anfrage an die Stahlbau Weidert KG in der Maienweg 11 a, 89081 Ulm schicken. Er hat zwar vor Jahren einmal mit einem Mitarbeiter namens Herr Krüger telefoniert, kann sich aber nicht mehr an dessen vollständigen Namen erinnern und weiß auch nicht, ob dieser noch dort arbeitet. Adressiere den Brief deshalb ganz allgemein an das Unternehmen, ohne einen persönlichen Ansprechpartner zu nennen.',
    senderLine: SENDER,
    lines: [
      {
        type: 'text',
        id: 'firma',
        caption: 'Zeile 6 – Firma',
        zone: 'anschrift',
        expected: 'Stahlbau Weidert KG',
        explanation:
          'Ist kein Ansprechpartner vorhanden, steht das Unternehmen direkt in der ersten Zeile – ohne Anrede und ohne den Zusatz „Firma“.',
      },
      {
        type: 'text',
        id: 'strasse',
        caption: 'Zeile 7 – Straße Hausnummer',
        zone: 'anschrift',
        expected: 'Maienweg 11 a',
        explanation: 'Ein Buchstabe in der Hausnummer wird durch ein Leerzeichen von der Zahl getrennt.',
      },
      {
        type: 'text',
        id: 'ort',
        caption: 'Zeile 8 – PLZ Ort',
        zone: 'anschrift',
        expected: '89081 Ulm',
        explanation: 'Die Postleitzahl steht immer vor dem Ort, ohne Komma dazwischen.',
      },
    ],
  },
  {
    id: 'unternehmen-mit-ansprechpartner',
    title: 'Unternehmen mit Ansprechpartner',
    difficulty: 'mittel',
    arbeitsauftrag:
      'Diesmal hat dein Chef mit der Stahlbau Weidert KG in der Maienweg 11 a, 89081 Ulm telefoniert und dabei direkt mit Herrn Stephan Breitner gesprochen, der die Anfrage bearbeiten wird. Der Brief soll deshalb gezielt an ihn persönlich gehen. Vergleiche beim Ausfüllen genau mit der vorherigen Aufgabe, in der kein Ansprechpartner bekannt war.',
    senderLine: SENDER,
    lines: [
      {
        type: 'text',
        id: 'firma',
        caption: 'Zeile 6 – Firma',
        zone: 'anschrift',
        expected: 'Stahlbau Weidert KG',
        explanation: 'Die Firmenbezeichnung steht immer über dem Empfängernamen.',
      },
      {
        type: 'text',
        id: 'name',
        caption: 'Zeile 7 – Anrede Titel Vorname Nachname',
        zone: 'anschrift',
        expected: 'Herrn Stephan Breitner',
        explanation:
          'Bei einem Unternehmen mit Ansprechpartner stehen Anrede und Name in EINER gemeinsamen Zeile – anders als bei einer Privatperson, wo die Anrede eine eigene Zeile bekommt.',
      },
      {
        type: 'text',
        id: 'strasse',
        caption: 'Zeile 8 – Straße Hausnummer',
        zone: 'anschrift',
        expected: 'Maienweg 11 a',
        explanation: 'Ein Buchstabe in der Hausnummer wird durch ein Leerzeichen von der Zahl getrennt.',
      },
      {
        type: 'text',
        id: 'ort',
        caption: 'Zeile 9 – PLZ Ort',
        zone: 'anschrift',
        expected: '89081 Ulm',
        explanation: 'Die Postleitzahl steht immer vor dem Ort, ohne Komma dazwischen.',
      },
    ],
  },
  {
    id: 'zusatz-und-vermerkzone',
    title: 'Zusatz- und Vermerkzone',
    difficulty: 'schwer',
    arbeitsauftrag:
      'Dein Chef händigt dir wichtige private Dokumente aus, die an Herrn Dr. Stephan Breitner, Birkenweg 11, 54344 Kenn gehen sollen. Weil der Empfang zweifelsfrei nachgewiesen werden muss, soll der Brief als Einschreiben mit Rückschein verschickt werden. Ergänze zuerst die passenden postalischen Vermerke, bevor du die eigentliche Anschrift ausfüllst.',
    senderLine: SENDER,
    lines: [
      {
        type: 'text',
        id: 'vermerk1',
        caption: 'Zusatz- und Vermerkzone – obere Zeile',
        expected: 'Einschreiben',
        zone: 'zusatz',
        explanation:
          'Mehrere postalische Vermerke werden untereinander aufgeführt. „Einschreiben“ steht hier über „mit Rückschein“.',
      },
      {
        type: 'text',
        id: 'vermerk2',
        caption: 'Zusatz- und Vermerkzone – untere Zeile (direkt über der Anschrift)',
        expected: 'mit Rückschein',
        zone: 'zusatz',
        explanation:
          'Auch bei mehreren Vermerken beginnt man auf der untersten Zeile der Zusatz- und Vermerkzone, also direkt über der eigentlichen Anschrift.',
      },
      {
        type: 'text',
        id: 'anrede',
        caption: 'Zeile 6 – Anrede',
        zone: 'anschrift',
        expected: 'Herrn',
        explanation: 'Die Anrede an männliche Empfänger lautet „Herrn“, nicht „Herr“.',
      },
      {
        type: 'text',
        id: 'name',
        caption: 'Zeile 7 – Titel Vorname Nachname',
        zone: 'anschrift',
        expected: 'Dr. Stephan Breitner',
        explanation: 'Titel stehen mit Leerzeichen vor dem Vornamen, die Anrede wird nicht wiederholt.',
      },
      {
        type: 'text',
        id: 'strasse',
        caption: 'Zeile 8 – Straße Hausnummer',
        zone: 'anschrift',
        expected: 'Birkenweg 11',
        explanation: 'Straße und Hausnummer stehen ohne Komma, die Hausnummer folgt der Straße.',
      },
      {
        type: 'text',
        id: 'ort',
        caption: 'Zeile 9 – PLZ Ort',
        zone: 'anschrift',
        expected: '54344 Kenn',
        explanation: 'Die Postleitzahl steht immer vor dem Ort, ohne Komma dazwischen.',
      },
    ],
  },
  {
    id: 'auslandsanschrift',
    title: 'Auslandsanschrift: Frankreich',
    difficulty: 'schwer',
    arbeitsauftrag:
      'Dein Chef hat auf einer Messe Herrn Stephan Breitner kennengelernt, der in Frankreich lebt, und verspricht ihm eine Broschüre zuzusenden. Auf seiner Visitenkarte steht die Adresse „11, Rue St. Antoine, 57600 Oeting, Frankreich“. Achte beim Übertragen dieser Auslandsanschrift auf die besonderen Regeln für Bestimmungsort und Bestimmungsland.',
    senderLine: SENDER,
    lines: [
      {
        type: 'text',
        id: 'anrede',
        caption: 'Zeile 6 – Anrede',
        zone: 'anschrift',
        expected: 'Herrn',
        explanation: 'Die Anrede an männliche Empfänger lautet „Herrn“, nicht „Herr“ – auch bei Auslandsbriefen.',
      },
      {
        type: 'text',
        id: 'name',
        caption: 'Zeile 7 – Vorname Nachname',
        zone: 'anschrift',
        expected: 'Stephan Breitner',
        explanation: 'Vor- und Nachname stehen in einer eigenen Zeile, ohne Wiederholung der Anrede.',
      },
      {
        type: 'text',
        id: 'strasse',
        caption: 'Zeile 8 – Straße Hausnummer',
        zone: 'anschrift',
        expected: '11, Rue St. Antoine',
        explanation:
          'Die Struktur der Adresse richtet sich nach dem Bestimmungsland. In Frankreich steht die Hausnummer vor der Straße.',
      },
      {
        type: 'text',
        id: 'ort',
        caption: 'Zeile 9 – PLZ Bestimmungsort',
        zone: 'anschrift',
        expected: '57600 OETING',
        explanation: 'Der Bestimmungsort wird bei Auslandssendungen in GROSSBUCHSTABEN geschrieben.',
      },
      {
        type: 'text',
        id: 'land',
        caption: 'Zeile 10 – Bestimmungsland',
        zone: 'anschrift',
        expected: 'FRANKREICH',
        explanation: 'Das Bestimmungsland wird bei Auslandssendungen ebenfalls in GROSSBUCHSTABEN geschrieben.',
      },
    ],
  },
  {
    id: 'privatperson-frau-einfach',
    title: 'Privatperson: Frau ohne Titel',
    difficulty: 'einfach',
    arbeitsauftrag:
      'Deine Chefin bittet dich, einen Dankesbrief an eine private Kundin zu adressieren. Es handelt sich um Anna Keller, die in der Lindenstraße 4 in 60313 Frankfurt wohnt. Erstelle das Anschriftenfeld und vergleiche danach die Anrede mit der bei einem männlichen Empfänger wie „Herrn“.',
    senderLine: SENDER,
    lines: [
      {
        type: 'text',
        id: 'anrede',
        caption: 'Zeile 6 – Anrede',
        zone: 'anschrift',
        expected: 'Frau',
        explanation: 'Die Anrede an weibliche Empfänger lautet „Frau“, unabhängig vom Familienstand.',
      },
      {
        type: 'text',
        id: 'name',
        caption: 'Zeile 7 – Vorname Nachname',
        zone: 'anschrift',
        expected: 'Anna Keller',
        explanation: 'Vor- und Nachname stehen in einer eigenen Zeile, ohne Wiederholung der Anrede.',
      },
      {
        type: 'text',
        id: 'strasse',
        caption: 'Zeile 8 – Straße Hausnummer',
        zone: 'anschrift',
        expected: 'Lindenstraße 4',
        explanation: 'Straße und Hausnummer stehen ohne Komma, die Hausnummer folgt der Straße.',
      },
      {
        type: 'text',
        id: 'ort',
        caption: 'Zeile 9 – PLZ Ort',
        zone: 'anschrift',
        expected: '60313 Frankfurt',
        explanation: 'Die Postleitzahl steht immer vor dem Ort, ohne Komma dazwischen.',
      },
    ],
  },
  {
    id: 'unternehmen-gmbh-ohne-ansprechpartner',
    title: 'Unternehmen (GmbH) ohne Ansprechpartner',
    difficulty: 'einfach',
    arbeitsauftrag:
      'Dein Chef möchte der Bäckerei Sonnenschein GmbH, Marktplatz 5, 79098 Freiburg ein allgemeines Angebot zuschicken. Er hat bisher noch nie mit jemandem aus dem Betrieb persönlich gesprochen und kennt daher auch niemanden dort namentlich. Adressiere den Brief entsprechend direkt an das Unternehmen.',
    senderLine: SENDER,
    lines: [
      {
        type: 'text',
        id: 'firma',
        caption: 'Zeile 6 – Firma',
        zone: 'anschrift',
        expected: 'Bäckerei Sonnenschein GmbH',
        explanation:
          'Ist kein Ansprechpartner vorhanden, steht das Unternehmen direkt in der ersten Zeile – ohne Anrede und ohne den Zusatz „Firma“.',
      },
      {
        type: 'text',
        id: 'strasse',
        caption: 'Zeile 7 – Straße Hausnummer',
        zone: 'anschrift',
        expected: 'Marktplatz 5',
        explanation: 'Straße und Hausnummer stehen ohne Komma, die Hausnummer folgt der Straße.',
      },
      {
        type: 'text',
        id: 'ort',
        caption: 'Zeile 8 – PLZ Ort',
        zone: 'anschrift',
        expected: '79098 Freiburg',
        explanation: 'Die Postleitzahl steht immer vor dem Ort, ohne Komma dazwischen.',
      },
    ],
  },
  {
    id: 'privatperson-doppeltitel',
    title: 'Privatperson mit mehreren Titeln',
    difficulty: 'mittel',
    arbeitsauftrag:
      'Ein ehemaliger Studienfreund deines Chefs hat inzwischen eine beachtliche akademische Laufbahn hingelegt: Prof. Dr. Michael Vogel wohnt heute im Ahornweg 9 in 70173 Stuttgart. Dein Chef möchte ihm eine Einladung zu einem Fachvortrag schicken und bittet dich, die Anschrift korrekt mit beiden Titeln in der richtigen Reihenfolge zu erstellen.',
    senderLine: SENDER,
    lines: [
      {
        type: 'text',
        id: 'anrede',
        caption: 'Zeile 6 – Anrede',
        zone: 'anschrift',
        expected: 'Herrn',
        explanation: 'Die Anrede an männliche Empfänger lautet „Herrn“, nicht „Herr“.',
      },
      {
        type: 'text',
        id: 'name',
        caption: 'Zeile 7 – Titel Vorname Nachname',
        zone: 'anschrift',
        expected: 'Prof. Dr. Michael Vogel',
        explanation:
          'Mehrere Titel stehen gemeinsam mit Leerzeichen vor dem Vornamen – in der Reihenfolge, in der sie geführt werden.',
      },
      {
        type: 'text',
        id: 'strasse',
        caption: 'Zeile 8 – Straße Hausnummer',
        zone: 'anschrift',
        expected: 'Ahornweg 9',
        explanation: 'Straße und Hausnummer stehen ohne Komma, die Hausnummer folgt der Straße.',
      },
      {
        type: 'text',
        id: 'ort',
        caption: 'Zeile 9 – PLZ Ort',
        zone: 'anschrift',
        expected: '70173 Stuttgart',
        explanation: 'Die Postleitzahl steht immer vor dem Ort, ohne Komma dazwischen.',
      },
    ],
  },
  {
    id: 'berufsbezeichnung-frau',
    title: 'Berufsbezeichnung bei einer Empfängerin',
    difficulty: 'mittel',
    arbeitsauftrag:
      'Für eine steuerliche Rückfrage soll dein Chef sich an Frau Steuerberaterin Julia Hoffmann wenden, deren Kanzlei sich im Rosenweg 2 in 04109 Leipzig befindet. Erstelle die Anschrift und denke daran, dass Berufs- bzw. Amtsbezeichnungen auch bei weiblichen Empfängerinnen hinter der Anrede stehen.',
    senderLine: SENDER,
    lines: [
      {
        type: 'text',
        id: 'anrede',
        caption: 'Zeile 6 – Anrede Berufsbezeichnung',
        zone: 'anschrift',
        expected: 'Frau Steuerberaterin',
        explanation: 'Berufs- bzw. Amtsbezeichnungen stehen in derselben Zeile hinter der Anrede.',
      },
      {
        type: 'text',
        id: 'name',
        caption: 'Zeile 7 – Vorname Nachname',
        zone: 'anschrift',
        expected: 'Julia Hoffmann',
        explanation: 'Vor- und Nachname stehen in einer eigenen Zeile, die Anrede wird nicht wiederholt.',
      },
      {
        type: 'text',
        id: 'strasse',
        caption: 'Zeile 8 – Straße Hausnummer',
        zone: 'anschrift',
        expected: 'Rosenweg 2',
        explanation: 'Straße und Hausnummer stehen ohne Komma, die Hausnummer folgt der Straße.',
      },
      {
        type: 'text',
        id: 'ort',
        caption: 'Zeile 9 – PLZ Ort',
        zone: 'anschrift',
        expected: '04109 Leipzig',
        explanation: 'Die Postleitzahl steht immer vor dem Ort, ohne Komma dazwischen.',
      },
    ],
  },
  {
    id: 'zusatzzone-privat',
    title: 'Vermerk „Privat“',
    difficulty: 'mittel',
    arbeitsauftrag:
      'Dein Chef schreibt seinem langjährigen Freund Thomas Krause, der im Feldweg 7 in 33098 Paderborn wohnt, einen persönlichen Brief zu einem sensiblen familiären Thema. Er möchte ausdrücklich sicherstellen, dass niemand anderes im Haushalt den Brief öffnet, bevor Herr Krause ihn selbst gelesen hat. Ergänze die Anschrift um den passenden Vermerk.',
    senderLine: SENDER,
    lines: [
      {
        type: 'text',
        id: 'vermerk',
        caption: 'Zusatz- und Vermerkzone – Zeile direkt über der Anschrift',
        expected: 'Privat',
        zone: 'zusatz',
        explanation:
          'Der Vermerk „Privat“ weist zusätzlich auf das Briefgeheimnis hin: In Deutschland darf niemand einen an eine andere Person adressierten Brief öffnen.',
      },
      {
        type: 'text',
        id: 'anrede',
        caption: 'Zeile 6 – Anrede',
        zone: 'anschrift',
        expected: 'Herrn',
        explanation: 'Die Anrede an männliche Empfänger lautet „Herrn“, nicht „Herr“.',
      },
      {
        type: 'text',
        id: 'name',
        caption: 'Zeile 7 – Vorname Nachname',
        zone: 'anschrift',
        expected: 'Thomas Krause',
        explanation: 'Vor- und Nachname stehen in einer eigenen Zeile, ohne Wiederholung der Anrede.',
      },
      {
        type: 'text',
        id: 'strasse',
        caption: 'Zeile 8 – Straße Hausnummer',
        zone: 'anschrift',
        expected: 'Feldweg 7',
        explanation: 'Straße und Hausnummer stehen ohne Komma, die Hausnummer folgt der Straße.',
      },
      {
        type: 'text',
        id: 'ort',
        caption: 'Zeile 9 – PLZ Ort',
        zone: 'anschrift',
        expected: '33098 Paderborn',
        explanation: 'Die Postleitzahl steht immer vor dem Ort, ohne Komma dazwischen.',
      },
    ],
  },
  {
    id: 'auslandsanschrift-oesterreich',
    title: 'Auslandsanschrift: Österreich',
    difficulty: 'mittel',
    arbeitsauftrag:
      'Bei einem Kongress in Wien hat dein Chef Herrn Alexander Berger kennengelernt, der ihm seine Visitenkarte mit der Adresse Ringstraße 12, 1010 Wien, Österreich gegeben hat. Erstelle die Auslandsanschrift und vergleiche sie mit der vorherigen Aufgabe zu Frankreich: Anders als dort ändert sich hier die Reihenfolge von Straße und Hausnummer nicht.',
    senderLine: SENDER,
    lines: [
      {
        type: 'text',
        id: 'anrede',
        caption: 'Zeile 6 – Anrede',
        zone: 'anschrift',
        expected: 'Herrn',
        explanation: 'Die Anrede an männliche Empfänger lautet „Herrn“, nicht „Herr“ – auch bei Auslandsbriefen.',
      },
      {
        type: 'text',
        id: 'name',
        caption: 'Zeile 7 – Vorname Nachname',
        zone: 'anschrift',
        expected: 'Alexander Berger',
        explanation: 'Vor- und Nachname stehen in einer eigenen Zeile, ohne Wiederholung der Anrede.',
      },
      {
        type: 'text',
        id: 'strasse',
        caption: 'Zeile 8 – Straße Hausnummer',
        zone: 'anschrift',
        expected: 'Ringstraße 12',
        explanation:
          'Die Struktur der Adresse richtet sich nach dem Bestimmungsland. Anders als in Frankreich behält Österreich die deutsche Reihenfolge Straße vor Hausnummer bei.',
      },
      {
        type: 'text',
        id: 'ort',
        caption: 'Zeile 9 – PLZ Bestimmungsort',
        zone: 'anschrift',
        expected: '1010 WIEN',
        explanation: 'Der Bestimmungsort wird bei Auslandssendungen in GROSSBUCHSTABEN geschrieben.',
      },
      {
        type: 'text',
        id: 'land',
        caption: 'Zeile 10 – Bestimmungsland',
        zone: 'anschrift',
        expected: 'ÖSTERREICH',
        explanation: 'Das Bestimmungsland wird bei Auslandssendungen ebenfalls in GROSSBUCHSTABEN geschrieben.',
      },
    ],
  },
  {
    id: 'auslandsanschrift-schweiz',
    title: 'Auslandsanschrift: Schweiz',
    difficulty: 'mittel',
    arbeitsauftrag:
      'Deine Chefin pflegt Geschäftskontakte in die Schweiz und möchte Frau Nicole Steiner, Bahnhofstrasse 22, 8001 Zürich, ein aktuelles Dokument zusenden. Erstelle die Anschrift und achte erneut darauf, dass Ort und Land bei Auslandssendungen in Großbuchstaben geschrieben werden.',
    senderLine: SENDER,
    lines: [
      {
        type: 'text',
        id: 'anrede',
        caption: 'Zeile 6 – Anrede',
        zone: 'anschrift',
        expected: 'Frau',
        explanation: 'Die Anrede an weibliche Empfänger lautet „Frau“ – auch bei Auslandsbriefen.',
      },
      {
        type: 'text',
        id: 'name',
        caption: 'Zeile 7 – Vorname Nachname',
        zone: 'anschrift',
        expected: 'Nicole Steiner',
        explanation: 'Vor- und Nachname stehen in einer eigenen Zeile, ohne Wiederholung der Anrede.',
      },
      {
        type: 'text',
        id: 'strasse',
        caption: 'Zeile 8 – Straße Hausnummer',
        zone: 'anschrift',
        expected: 'Bahnhofstrasse 22',
        explanation: 'Straße und Hausnummer stehen ohne Komma, die Hausnummer folgt der Straße.',
      },
      {
        type: 'text',
        id: 'ort',
        caption: 'Zeile 9 – PLZ Bestimmungsort',
        zone: 'anschrift',
        expected: '8001 ZÜRICH',
        explanation: 'Der Bestimmungsort wird bei Auslandssendungen in GROSSBUCHSTABEN geschrieben.',
      },
      {
        type: 'text',
        id: 'land',
        caption: 'Zeile 10 – Bestimmungsland',
        zone: 'anschrift',
        expected: 'SCHWEIZ',
        explanation: 'Das Bestimmungsland wird bei Auslandssendungen ebenfalls in GROSSBUCHSTABEN geschrieben.',
      },
    ],
  },
  {
    id: 'postfach-ungerade',
    title: 'Postfach mit ungerader Ziffernzahl',
    difficulty: 'schwer',
    arbeitsauftrag:
      'Dein Chef möchte vertrauliche Vertragsunterlagen an Herrn Dr. Markus Lindner schicken, dessen Praxis in 50667 Köln ausschließlich über das Postfach 12345 erreichbar ist. Erstelle die vollständige Anschrift – überlege dabei genau, wie eine Postfachnummer mit einer ungeraden Anzahl an Ziffern gegliedert wird.',
    senderLine: SENDER,
    lines: [
      {
        type: 'text',
        id: 'anrede',
        caption: 'Zeile 6 – Anrede',
        zone: 'anschrift',
        expected: 'Herrn',
        explanation: 'Die Anrede an männliche Empfänger lautet „Herrn“, nicht „Herr“.',
      },
      {
        type: 'text',
        id: 'name',
        caption: 'Zeile 7 – Titel Vorname Nachname',
        zone: 'anschrift',
        expected: 'Dr. Markus Lindner',
        explanation: 'Titel stehen mit Leerzeichen vor dem Vornamen.',
      },
      {
        type: 'text',
        id: 'postfach',
        caption: 'Zeile 8 – Straße Hausnummer (oder Postfach)',
        zone: 'anschrift',
        expected: 'Postfach 1 23 45',
        explanation:
          'Postfachnummern werden von rechts nach links in Zweiergruppen gegliedert. Bleibt eine einzelne Ziffer übrig, steht sie allein ganz vorne.',
      },
      {
        type: 'text',
        id: 'ort',
        caption: 'Zeile 9 – PLZ Ort',
        zone: 'anschrift',
        expected: '50667 Köln',
        explanation: 'Die Postleitzahl steht immer vor dem Ort, ohne Komma dazwischen.',
      },
    ],
  },
  {
    id: 'unternehmen-mit-titel-ansprechpartner',
    title: 'Unternehmen mit Ansprechpartner und Titel',
    difficulty: 'schwer',
    arbeitsauftrag:
      'Für eine gerichtliche Auseinandersetzung beauftragt dein Chef die Kanzlei Berger & Partner in der Kaiserstraße 15, 60311 Frankfurt. Zuständig für den Fall ist dort Herr Dr. Felix Berger, mit dem dein Chef bereits telefonisch gesprochen hat. Erstelle die Anschrift so, dass sowohl das Unternehmen als auch der Ansprechpartner mit seinem akademischen Titel korrekt erscheinen.',
    senderLine: SENDER,
    lines: [
      {
        type: 'text',
        id: 'firma',
        caption: 'Zeile 6 – Firma',
        zone: 'anschrift',
        expected: 'Kanzlei Berger & Partner',
        explanation: 'Die Firmenbezeichnung steht immer über dem Empfängernamen.',
      },
      {
        type: 'text',
        id: 'name',
        caption: 'Zeile 7 – Anrede Titel Vorname Nachname',
        zone: 'anschrift',
        expected: 'Herrn Dr. Felix Berger',
        explanation:
          'Bei einem Unternehmen mit Ansprechpartner stehen Anrede, Titel und Name in einer gemeinsamen Zeile; der Titel steht dabei mit Leerzeichen vor dem Vornamen.',
      },
      {
        type: 'text',
        id: 'strasse',
        caption: 'Zeile 8 – Straße Hausnummer',
        zone: 'anschrift',
        expected: 'Kaiserstraße 15',
        explanation: 'Straße und Hausnummer stehen ohne Komma, die Hausnummer folgt der Straße.',
      },
      {
        type: 'text',
        id: 'ort',
        caption: 'Zeile 9 – PLZ Ort',
        zone: 'anschrift',
        expected: '60311 Frankfurt',
        explanation: 'Die Postleitzahl steht immer vor dem Ort, ohne Komma dazwischen.',
      },
    ],
  },
  {
    id: 'zusatzzone-einschreiben-privat',
    title: 'Einschreiben und „Privat“ kombiniert',
    difficulty: 'schwer',
    arbeitsauftrag:
      'Dein Chef möchte Frau Dr. Sabine Wolf, Gartenweg 3, 22303 Hamburg, ein wichtiges persönliches Dokument zukommen lassen. Der Empfang soll nachweisbar sein, gleichzeitig soll aber niemand außer Frau Wolf selbst den Umschlag öffnen. Ergänze die Anschrift um beide notwendigen Vermerke in der richtigen Reihenfolge.',
    senderLine: SENDER,
    lines: [
      {
        type: 'text',
        id: 'vermerk1',
        caption: 'Zusatz- und Vermerkzone – obere Zeile',
        expected: 'Einschreiben',
        zone: 'zusatz',
        explanation: 'Mehrere postalische Vermerke werden untereinander aufgeführt. „Einschreiben“ steht hier über „Privat“.',
      },
      {
        type: 'text',
        id: 'vermerk2',
        caption: 'Zusatz- und Vermerkzone – untere Zeile (direkt über der Anschrift)',
        expected: 'Privat',
        zone: 'zusatz',
        explanation:
          'Auch bei mehreren Vermerken beginnt man auf der untersten Zeile der Zusatz- und Vermerkzone, also direkt über der eigentlichen Anschrift.',
      },
      {
        type: 'text',
        id: 'anrede',
        caption: 'Zeile 6 – Anrede',
        zone: 'anschrift',
        expected: 'Frau',
        explanation: 'Die Anrede an weibliche Empfänger lautet „Frau“, nicht „Frauen“.',
      },
      {
        type: 'text',
        id: 'name',
        caption: 'Zeile 7 – Titel Vorname Nachname',
        zone: 'anschrift',
        expected: 'Dr. Sabine Wolf',
        explanation: 'Titel stehen mit Leerzeichen vor dem Vornamen, die Anrede wird nicht wiederholt.',
      },
      {
        type: 'text',
        id: 'strasse',
        caption: 'Zeile 8 – Straße Hausnummer',
        zone: 'anschrift',
        expected: 'Gartenweg 3',
        explanation: 'Straße und Hausnummer stehen ohne Komma, die Hausnummer folgt der Straße.',
      },
      {
        type: 'text',
        id: 'ort',
        caption: 'Zeile 9 – PLZ Ort',
        zone: 'anschrift',
        expected: '22303 Hamburg',
        explanation: 'Die Postleitzahl steht immer vor dem Ort, ohne Komma dazwischen.',
      },
    ],
  },
  {
    id: 'behoerde-buergeramt',
    title: 'Behörde mit Fachabteilung',
    difficulty: 'einfach',
    arbeitsauftrag:
      'Dein Chef benötigt eine neue Gewerbeanmeldung und schickt die Unterlagen an die Stadtverwaltung Trier. Zuständig ist dort laut Internetseite der Stadt nicht das Rathaus allgemein, sondern konkret das Bürgeramt, das sich am Rathausplatz 1 in 54290 Trier befindet. Erstelle die Anschrift so, dass sowohl die Behörde als auch die zuständige Abteilung erkennbar sind – einen persönlichen Ansprechpartner kennt dein Chef nicht.',
    senderLine: SENDER,
    lines: [
      {
        type: 'text',
        id: 'firma',
        caption: 'Zeile 6 – Behörde',
        zone: 'anschrift',
        expected: 'Stadtverwaltung Trier',
        explanation:
          'Bei Behörden steht der Name der Institution wie eine Firmenbezeichnung in der ersten Zeile der Anschrift.',
      },
      {
        type: 'text',
        id: 'abteilung',
        caption: 'Zeile 7 – Abteilung',
        zone: 'anschrift',
        expected: 'Bürgeramt',
        explanation:
          'Ist eine bestimmte Abteilung zuständig, aber kein persönlicher Ansprechpartner bekannt, wird die Abteilung in einer eigenen Zeile unter dem Namen der Institution genannt.',
      },
      {
        type: 'text',
        id: 'strasse',
        caption: 'Zeile 8 – Straße Hausnummer',
        zone: 'anschrift',
        expected: 'Rathausplatz 1',
        explanation: 'Straße und Hausnummer stehen ohne Komma, die Hausnummer folgt der Straße.',
      },
      {
        type: 'text',
        id: 'ort',
        caption: 'Zeile 9 – PLZ Ort',
        zone: 'anschrift',
        expected: '54290 Trier',
        explanation: 'Die Postleitzahl steht immer vor dem Ort, ohne Komma dazwischen.',
      },
    ],
  },
  {
    id: 'unternehmen-niederlande',
    title: 'Auslandsanschrift: Niederlande',
    difficulty: 'mittel',
    arbeitsauftrag:
      'Dein Chef hat auf einer Handelsmesse in Utrecht Kontakt zu einem Elektronikgroßhändler aufgenommen und möchte diesem ein Angebot zusenden. Auf dem Prospekt des Unternehmens steht: Van der Berg Elektronik B.V., Keizersgracht 45, 1015 CJ Amsterdam, Niederlande. Da dein Chef mit niemandem persönlich gesprochen hat, adressiere den Brief an das Unternehmen selbst.',
    senderLine: SENDER,
    lines: [
      {
        type: 'text',
        id: 'firma',
        caption: 'Zeile 6 – Firma',
        zone: 'anschrift',
        expected: 'Van der Berg Elektronik B.V.',
        explanation:
          'Ist kein Ansprechpartner bekannt, steht das Unternehmen direkt in der ersten Zeile – auch bei Auslandsanschriften.',
      },
      {
        type: 'text',
        id: 'strasse',
        caption: 'Zeile 7 – Straße Hausnummer',
        zone: 'anschrift',
        expected: 'Keizersgracht 45',
        explanation:
          'Die Niederlande behalten wie Deutschland die Reihenfolge Straße vor Hausnummer bei.',
      },
      {
        type: 'text',
        id: 'ort',
        caption: 'Zeile 8 – PLZ Bestimmungsort',
        zone: 'anschrift',
        expected: '1015 CJ AMSTERDAM',
        explanation:
          'Auch eine aus Ziffern und Buchstaben bestehende ausländische Postleitzahl wird vor dem Bestimmungsort genannt; dieser wird bei Auslandssendungen in GROSSBUCHSTABEN geschrieben.',
      },
      {
        type: 'text',
        id: 'land',
        caption: 'Zeile 9 – Bestimmungsland',
        zone: 'anschrift',
        expected: 'NIEDERLANDE',
        explanation: 'Das Bestimmungsland wird bei Auslandssendungen ebenfalls in GROSSBUCHSTABEN geschrieben.',
      },
    ],
  },
  {
    id: 'akademie-doppeltitel-frau',
    title: 'Universität: Ansprechpartnerin mit Doppeltitel',
    difficulty: 'schwer',
    arbeitsauftrag:
      'Für ein Forschungsprojekt möchte dein Chef mit der Universität Leipzig zusammenarbeiten. Empfohlen wurde ihm dafür Frau Prof. Dr. Julia Bergmann vom Institut in der Ritterstraße 26, 04109 Leipzig, die als einzige Professorin des Fachbereichs für das Thema zuständig ist – ein zweiter, jüngerer Mitarbeiter des Instituts wurde ihm zwar auch genannt, ist für diese Anfrage aber nicht zuständig. Adressiere den Brief an die Universität mit Frau Prof. Dr. Bergmann als Ansprechpartnerin.',
    senderLine: SENDER,
    lines: [
      {
        type: 'text',
        id: 'firma',
        caption: 'Zeile 6 – Institution',
        zone: 'anschrift',
        expected: 'Universität Leipzig',
        explanation: 'Die Institution steht wie eine Firmenbezeichnung über dem Namen der Ansprechpartnerin.',
      },
      {
        type: 'text',
        id: 'name',
        caption: 'Zeile 7 – Anrede Titel Vorname Nachname',
        zone: 'anschrift',
        expected: 'Frau Prof. Dr. Julia Bergmann',
        explanation:
          'Bei einer Institution mit Ansprechpartnerin stehen Anrede, alle Titel (in ihrer Reihenfolge) und Name in einer gemeinsamen Zeile.',
      },
      {
        type: 'text',
        id: 'strasse',
        caption: 'Zeile 8 – Straße Hausnummer',
        zone: 'anschrift',
        expected: 'Ritterstraße 26',
        explanation: 'Straße und Hausnummer stehen ohne Komma, die Hausnummer folgt der Straße.',
      },
      {
        type: 'text',
        id: 'ort',
        caption: 'Zeile 9 – PLZ Ort',
        zone: 'anschrift',
        expected: '04109 Leipzig',
        explanation: 'Die Postleitzahl steht immer vor dem Ort, ohne Komma dazwischen.',
      },
    ],
  },
  {
    id: 'auslandsanschrift-grossbritannien',
    title: 'Auslandsanschrift: Großbritannien',
    difficulty: 'schwer',
    arbeitsauftrag:
      'Dein Chef pflegt eine Geschäftsbeziehung nach London und möchte Herrn James Whitmore ein aktualisiertes Vertragsdokument schicken. Auf seiner E-Mail-Signatur findet sich die Adresse: 22 Baker Street, London NW1 6XE, United Kingdom. Übertrage diese britische Anschrift korrekt in das deutsche Anschriftenfeld – achte dabei besonders auf die Reihenfolge von Hausnummer und Straße sowie auf die Position der Postleitzahl.',
    senderLine: SENDER,
    lines: [
      {
        type: 'text',
        id: 'anrede',
        caption: 'Zeile 6 – Anrede',
        zone: 'anschrift',
        expected: 'Herrn',
        explanation: 'Die Anrede an männliche Empfänger lautet „Herrn“, nicht „Herr“ – auch bei Auslandsbriefen.',
      },
      {
        type: 'text',
        id: 'name',
        caption: 'Zeile 7 – Vorname Nachname',
        zone: 'anschrift',
        expected: 'James Whitmore',
        explanation: 'Vor- und Nachname stehen in einer eigenen Zeile, ohne Wiederholung der Anrede.',
      },
      {
        type: 'text',
        id: 'strasse',
        caption: 'Zeile 8 – Straße Hausnummer',
        zone: 'anschrift',
        expected: '22 Baker Street',
        explanation:
          'In Großbritannien steht die Hausnummer wie in Frankreich vor dem Straßennamen, nicht dahinter wie in Deutschland.',
      },
      {
        type: 'text',
        id: 'ort',
        caption: 'Zeile 9 – Bestimmungsort mit Postleitzahl',
        zone: 'anschrift',
        expected: 'LONDON NW1 6XE',
        explanation:
          'In Großbritannien folgt die Postleitzahl auf den Ortsnamen statt davor zu stehen. Beides wird bei Auslandssendungen in GROSSBUCHSTABEN geschrieben.',
      },
      {
        type: 'text',
        id: 'land',
        caption: 'Zeile 10 – Bestimmungsland',
        zone: 'anschrift',
        expected: 'GROSSBRITANNIEN',
        explanation: 'Das Bestimmungsland wird bei Auslandssendungen ebenfalls in GROSSBUCHSTABEN geschrieben.',
      },
    ],
  },
];

export function getAnschriftenfeldTaskById(id: string) {
  return ANSCHRIFTENFELD_TASKS.find((task) => task.id === id);
}
